version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/ethereum"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/viewer"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/animation_url"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/garage"
    schedule:
      interval: "monthly"
