linters-settings:
  revive:
    ignore-generated-header: false
    severity: warning
    confidence: 0.8
    errorCode: 0
    warningCode: 0
    rules:
      - name:  blank-imports
      - name:  context-as-argument
      - name:  context-keys-type
      - name:  dot-imports
      - name:  error-return
      - name:  error-strings
      - name:  error-naming
      - name:  exported
      - name:  if-return
      - name:  increment-decrement
      - name:  var-naming
      - name:  var-declaration
      - name:  package-comments
        disabled: true
      - name:  range
      - name:  receiver-naming
      - name:  time-naming
      - name:  unexported-return
      - name:  indent-error-flow
      - name:  errorf
      - name:  empty-block
      - name:  superfluous-else
      - name:  unused-parameter
      - name:  unreachable-code
      - name:  redefines-builtin-id
  misspell:
    locale: US

linters:
  enable:
    - revive
    - misspell
    - bodyclose
    - unconvert
    - goconst
    - goimports
    - unparam
    - whitespace
    - godot
    - lll

issues:
  exclude-use-default: false

  exclude:
    - stutters

run:
  timeout: 30m
