import React from "react";
import { Box, useToken } from "@chakra-ui/react";

// Takes an SVG component generated by svgr
// and creates an icon with round background and 20% padding
export const RoundSvgIcon = ({
  Component,
  bgColor,
  hoverBgColor,
  color,
  size,
}: {
  Component: React.FunctionComponent<React.ComponentProps<"svg">>;
  bgColor?: string;
  hoverBgColor?: string;
  color?: string;
  size: number;
}) => {
  const [primaryColor, paperColor] = useToken("colors", ["primary", "paper"]);

  bgColor = bgColor ?? primaryColor;
  hoverBgColor = hoverBgColor ?? "#7ddbda";
  color = color ?? paperColor;

  return (
    <Box
      width={`${size}px`}
      height={`${size}px`}
      sx={{
        background: bgColor,
        borderRadius: size,
        border: "0px",
        padding: `${size / 5}px`,
        _hover: {
          background: hoverBgColor,
        },
      }}
    >
      <Component width="100%" height="100%" style={{ fill: color }} />
    </Box>
  );
};
