name: Test

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: test-${{github.ref}}
  cancel-in-progress: true

jobs:
  test:
    name: Test API
    strategy:
      matrix:
        go-version: [1.16.x, v1.17.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            %LocalAppData%\go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Test
        run: make test
      - name: Install and generate frontend
        working-directory: ./client
        run: |
          npm install
          npm run generate
      - name: Test frontend
        working-directory: ./client
        run: |
          npm test
  test-app:
    name: Test App
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install and generate
      working-directory: ./client
      run: |
        npm install
        npm run generate
    - name: Test
      working-directory: ./client
      run: |
        npm test
  test-ethereum:
    name: Test Ethereum
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ethereum
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Cache
        uses: actions/cache@v1
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Setup Node Environment ⬢
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
